### ISSUE TITLE
[Fund Request ] User type (SME) Submit application for funds

### ISSUE THREAD

**Issue by OluwmayowaF** [BuildForSDG/Team-083-Backend#12]
**As a verified SME, I want to be able to **
- Submit an application for funds.
- View the status of my application. 
- View Previous applications.

**Comment by ezehlivinus** [comment]
This description is not it. Founder do not submit application. Check the db schema for more info.

When funder funds an SME, that is when an SME can make a fundRequest.

Fund Request is the process of asking the system to release some fund, from the startup fund, for a particular milestone in a given month.

**Example FunderA  has funded SME-A with the sum 500,000NGN, in the month of May. Towards May 27th, the Startup can make a fund request of 100,000NGN for the month of June. With a certain milestone.
Their balance 400,000NGN.**



For startup seeking for fund, their profile has field called, ask. The ask field is the amount they are asking from a funder: say 750,000. The PitchDeck field contain the link to their presentation slide (investor pitch deck), one of the slide on it is the Ask, which restate the amount they are asking for,  that further tells how they intended to use this fund...
